/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PublicImport } from './routes/_public'
import { Route as PrivateImport } from './routes/_private'
import { Route as PublicIndexImport } from './routes/_public/index'
import { Route as PrivateUsersImport } from './routes/_private/users'
import { Route as PrivateChatImport } from './routes/_private/chat'
import { Route as PrivateCalendarImport } from './routes/_private/calendar'
import { Route as PrivateTestsIndexImport } from './routes/_private/tests/index'
import { Route as PrivateAnswersIndexImport } from './routes/_private/answers/index'
import { Route as PrivateTestsMapiImport } from './routes/_private/tests/mapi'
import { Route as PrivateAnswersIdImport } from './routes/_private/answers/$id'

// Create/Update Routes

const PublicRoute = PublicImport.update({
  id: '/_public',
  getParentRoute: () => rootRoute,
} as any)

const PrivateRoute = PrivateImport.update({
  id: '/_private',
  getParentRoute: () => rootRoute,
} as any)

const PublicIndexRoute = PublicIndexImport.update({
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)

const PrivateUsersRoute = PrivateUsersImport.update({
  path: '/users',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateChatRoute = PrivateChatImport.update({
  path: '/chat',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateCalendarRoute = PrivateCalendarImport.update({
  path: '/calendar',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateTestsIndexRoute = PrivateTestsIndexImport.update({
  path: '/tests/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateAnswersIndexRoute = PrivateAnswersIndexImport.update({
  path: '/answers/',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateTestsMapiRoute = PrivateTestsMapiImport.update({
  path: '/tests/mapi',
  getParentRoute: () => PrivateRoute,
} as any)

const PrivateAnswersIdRoute = PrivateAnswersIdImport.update({
  path: '/answers/$id',
  getParentRoute: () => PrivateRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PrivateImport
      parentRoute: typeof rootRoute
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicImport
      parentRoute: typeof rootRoute
    }
    '/_private/calendar': {
      id: '/_private/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof PrivateCalendarImport
      parentRoute: typeof PrivateImport
    }
    '/_private/chat': {
      id: '/_private/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof PrivateChatImport
      parentRoute: typeof PrivateImport
    }
    '/_private/users': {
      id: '/_private/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof PrivateUsersImport
      parentRoute: typeof PrivateImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexImport
      parentRoute: typeof PublicImport
    }
    '/_private/answers/$id': {
      id: '/_private/answers/$id'
      path: '/answers/$id'
      fullPath: '/answers/$id'
      preLoaderRoute: typeof PrivateAnswersIdImport
      parentRoute: typeof PrivateImport
    }
    '/_private/tests/mapi': {
      id: '/_private/tests/mapi'
      path: '/tests/mapi'
      fullPath: '/tests/mapi'
      preLoaderRoute: typeof PrivateTestsMapiImport
      parentRoute: typeof PrivateImport
    }
    '/_private/answers/': {
      id: '/_private/answers/'
      path: '/answers'
      fullPath: '/answers'
      preLoaderRoute: typeof PrivateAnswersIndexImport
      parentRoute: typeof PrivateImport
    }
    '/_private/tests/': {
      id: '/_private/tests/'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof PrivateTestsIndexImport
      parentRoute: typeof PrivateImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  PrivateRoute: PrivateRoute.addChildren({
    PrivateCalendarRoute,
    PrivateChatRoute,
    PrivateUsersRoute,
    PrivateAnswersIdRoute,
    PrivateTestsMapiRoute,
    PrivateAnswersIndexRoute,
    PrivateTestsIndexRoute,
  }),
  PublicRoute: PublicRoute.addChildren({ PublicIndexRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_private",
        "/_public"
      ]
    },
    "/_private": {
      "filePath": "_private.tsx",
      "children": [
        "/_private/calendar",
        "/_private/chat",
        "/_private/users",
        "/_private/answers/$id",
        "/_private/tests/mapi",
        "/_private/answers/",
        "/_private/tests/"
      ]
    },
    "/_public": {
      "filePath": "_public.tsx",
      "children": [
        "/_public/"
      ]
    },
    "/_private/calendar": {
      "filePath": "_private/calendar.tsx",
      "parent": "/_private"
    },
    "/_private/chat": {
      "filePath": "_private/chat.tsx",
      "parent": "/_private"
    },
    "/_private/users": {
      "filePath": "_private/users.tsx",
      "parent": "/_private"
    },
    "/_public/": {
      "filePath": "_public/index.tsx",
      "parent": "/_public"
    },
    "/_private/answers/$id": {
      "filePath": "_private/answers/$id.tsx",
      "parent": "/_private"
    },
    "/_private/tests/mapi": {
      "filePath": "_private/tests/mapi.tsx",
      "parent": "/_private"
    },
    "/_private/answers/": {
      "filePath": "_private/answers/index.tsx",
      "parent": "/_private"
    },
    "/_private/tests/": {
      "filePath": "_private/tests/index.tsx",
      "parent": "/_private"
    }
  }
}
ROUTE_MANIFEST_END */
