/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as rootIndexImport } from './routes/(root)/index'
import { Route as rootAboutImport } from './routes/(root)/about'

// Create/Update Routes

const rootIndexRoute = rootIndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const rootAboutRoute = rootAboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(root)/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof rootAboutImport
      parentRoute: typeof rootRoute
    }
    '/(root)/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof rootIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  rootAboutRoute,
  rootIndexRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/about",
        "/"
      ]
    },
    "/about": {
      "filePath": "(root)/about.tsx"
    },
    "/": {
      "filePath": "(root)/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
