export enum Permisos {
  VER_HOME = "Ver home",
  VER_TESTS_ASIGNACION = "Ver tests (asignación)",
  VER_TESTS_RESOLUCION = "Ver tests (resolución)",
  COMPARTIR_TEST = "Compartir test",
  VER_RESULTADOS = "Ver resultados",
  VER_PLANTILLAS = "Ver plantillas",
  VER_CALENDARIO = "Ver calendario",
  VER_USUARIOS = "Ver usuarios",
  CREAR_TEST = "Crear test",
  EDITAR_TEST = "Editar test",
  CONFIGURAR = "Configurar",
  VER_CITAS = "Ver citas",
  VER_BLOGS = "Ver blogs",
  CREAR_BLOGS = "Crear blogs",
  DESTACAR_BLOGS = "Destacar blogs",
  VER_REPORTES = "Ver reportes",
  VER_TODAS_LAS_CARPETAS = "Ver todas las carpetas",
  ADMINISTRAR_PACIENTES = "Administrar pacientes",
}
