on:
  push:
    branches:
      - main

name: Deploy client to Cpanel 🚀
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Build the project
        working-directory: ./client
        run: npm run build

      - name: Deploy to Cpanel
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.CPANEL_SERVER }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          local-dir: ./client/dist/
          dangerous-clean-slate: true
